[2025-04-29T17:44:16.482+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T17:44:16.489+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_history_sanjose.load_weather_history scheduled__2025-04-26T00:00:00+00:00 [queued]>
[2025-04-29T17:44:16.492+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_history_sanjose.load_weather_history scheduled__2025-04-26T00:00:00+00:00 [queued]>
[2025-04-29T17:44:16.492+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-29T17:44:16.497+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_history> on 2025-04-26 00:00:00+00:00
[2025-04-29T17:44:16.502+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1677) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T17:44:16.505+0000] {standard_task_runner.py:72} INFO - Started process 1688 to run task
[2025-04-29T17:44:16.504+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_history_sanjose', 'load_weather_history', 'scheduled__2025-04-26T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/weather_history_sj.py', '--cfg-path', '/tmp/tmpy_l18_2e']
[2025-04-29T17:44:16.506+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask load_weather_history
[2025-04-29T17:44:16.529+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_history_sanjose.load_weather_history scheduled__2025-04-26T00:00:00+00:00 [running]> on host 975c9d700231
[2025-04-29T17:44:16.580+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_history_sanjose' AIRFLOW_CTX_TASK_ID='load_weather_history' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-26T00:00:00+00:00'
[2025-04-29T17:44:16.581+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-29T17:44:16.594+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-29T17:44:16.595+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-04-29T17:44:16.597+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-29T17:44:16.598+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-29T17:44:17.411+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T17:44:17.572+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T17:48:16.014+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T17:48:16.036+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-29T17:48:16.052+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-29T17:48:16.053+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_history_sanjose, task_id=load_weather_history, run_id=scheduled__2025-04-26T00:00:00+00:00, execution_date=20250426T000000, start_date=20250429T174416, end_date=20250429T174816
[2025-04-29T17:48:16.115+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-29T17:48:16.140+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T17:48:16.141+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
