[2025-05-01T05:21:26.931+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-01T05:21:26.938+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_history_sanjose.load_weather_history manual__2025-05-01T05:21:14.491825+00:00 [queued]>
[2025-05-01T05:21:26.942+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_history_sanjose.load_weather_history manual__2025-05-01T05:21:14.491825+00:00 [queued]>
[2025-05-01T05:21:26.942+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-01T05:21:26.947+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_history> on 2025-05-01 05:21:14.491825+00:00
[2025-05-01T05:21:26.952+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7624) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-01T05:21:26.951+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_history_sanjose', 'load_weather_history', 'manual__2025-05-01T05:21:14.491825+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/weather_history_sj.py', '--cfg-path', '/tmp/tmpufwf6gse']
[2025-05-01T05:21:26.953+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask load_weather_history
[2025-05-01T05:21:26.953+0000] {standard_task_runner.py:72} INFO - Started process 7627 to run task
[2025-05-01T05:21:26.973+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_history_sanjose.load_weather_history manual__2025-05-01T05:21:14.491825+00:00 [running]> on host a70fb8b05a55
[2025-05-01T05:21:27.009+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_history_sanjose' AIRFLOW_CTX_TASK_ID='load_weather_history' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T05:21:14.491825+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T05:21:14.491825+00:00'
[2025-05-01T05:21:27.009+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-01T05:21:27.014+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-01T05:21:27.014+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-01T05:21:27.015+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-01T05:21:27.015+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-01T05:21:28.299+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T05:21:28.506+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T05:30:24.089+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-01T05:30:24.096+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-01T05:30:24.097+0000] {process_utils.py:132} INFO - Sending 15 to group 7627. PIDs of all processes in the group: [7627]
[2025-05-01T05:30:24.098+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 7627
[2025-05-01T05:30:24.098+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-01T05:30:24.133+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-01T05:30:24.155+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=7627, status='terminated', exitcode=0, started='05:21:26') (7627) terminated with exit code 0
